server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/BookingService"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "namhoang0505pro@gmail.com"
    password: "mzaz jytw mhcf ghci"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 87846938671-76pcjrb3ucf7ngmkai7b2qni7uvrn9qt.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "https://e8e8-118-69-182-149.ngrok-free.app/login/oauth2/code/google"  # Added redirect-uri
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
jwt:
  signerKey: "3aF+lAiyA/tEAeeBtmlou0RwdTwXx0lU6SjH0MYBR7DRt9vyJzlv66uqnqHMP2NW"
  valid-duration: 3600
  refreshable-duration: 36000

beautya:
  feedback:
    link: https://e8e8-118-69-182-149.ngrok-free.app/BookingService/api/feedbacks

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

booking:
  auto-cancel:
    minutes: 30